name: Astronomer CI - Deploy code
on:
  push:
    branches:
      - main

env:
  ## Sets Deployment API key credentials as environment variables
  ASTRONOMER_KEY_ID: "IMYDSEKSMBWb3A3p0VtvFcINJT5yQ1RO"
  ASTRONOMER_KEY_SECRET: "_BXxayoiSXEX8d79sBrVhHIZEoMrmIAWZWu_pBf9ylfy156ugPl1u2KdEzLgl6mG"
  ASTRONOMER_DEPLOYMENT_ID: ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}
  DAG_FOLDER: dags/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    # Determine if only DAGs have changes 
    - name: Get Deployment Type
      run: |
        files=$(git diff --name-only HEAD^..HEAD)
        dags_only=1

        for file in $files; do
          if [[ $file != "$DAG_FOLDER"* ]]; then
            echo "$file is not a dag, triggering a full image build"
            dags_only=0
            break
          fi
        done

        echo "DAGS_ONLY=$dags_only" >> $GITHUB_OUTPUT
      id: deployment-type
    # Install Astro CLI
    - name: Install Astro CLI
      run: |
        curl -sSL https://install.astronomer.io | sudo bash -s
    # If only DAGs changed, do a DAG-only deploy
    - name: DAG Deploy to Astro
      if: steps.deployment-type.outputs.DAGS_ONLY == 1
      run: |
        astro deploy --dags
    # If any other files changed, deploy the entire Astro project
    - name: Image and DAG Deploy to Astro
      if: steps.deployment-type.outputs.DAGS_ONLY == 0
      run: |
        astro deploy 