name: Merging Staging Into Main
on:
  workflow_run:
    workflows: ['Staging Deploy']
    types:
      - completed
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    environment: repo_token
    steps:
      - uses: actions/checkout@master
      - name: Merge staging to main 
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}